### ISSUE TITLE
Videos marked as partially watched on YouTube

### ISSUE THREAD

**Issue by w3ricardo** [highstrike/youtube-watched#2]
When downloading long videos from YouTube (over 25 minutes) and using the option --mark-watched, only the start of the video is marked as watched (the first 5 minutes or so).

**Comment by highstrike** [comment]
Im sorry, what do you mean when you're downloading youtube videos, and what option --mark-watched? I think you got the wrong repository :)

My script marks videos as watched on youtube even if you didn't watch them to the end (eg. skipping sponsor spots). And it does so on the website itself, as a visual cue.
